Traceback (most recent call last):
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Substitution'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/miller_lab/csxue/bayes-power-sig/scripts/infer-loadings-only.py", line 227, in <module>
    main()
  File "/net/rcstorenfs02/ifs/rc_labs/miller_lab/csxue/bayes-power-sig/scripts/infer-loadings-only.py", line 61, in main
    full_df = load_sbs_data(args.data, args.plain)
  File "/net/rcstorenfs02/ifs/rc_labs/miller_lab/csxue/bayes-power-sig/scripts/infer-loadings-only.py", line 157, in load_sbs_data
    data.columns = data.loc['Substitution']
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3773, in xs
    loc = index.get_loc(key)
  File "/n/home00/csxue/.conda/envs/mutsig-venv/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'Substitution'
